services:
  postgres:
    container_name: ms_test__pg_sql
    image: postgres
    environment:
      POSTGRES_USER: martin
      POSTGRES_PASSWORD: martin
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

    restart: unless-stopped

volumes:
  postgres: